/*
 * AttributeSelectorFrame.java
 *
 * Created on 9. joulukuuta 2007, 15:35
 */
package org.quickclient.gui;

import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;

import javax.swing.DefaultListModel;
import javax.swing.JButton;

import org.quickclient.classes.DocuSessionManager;
import org.quickclient.classes.VisibleAttributeData;

import net.miginfocom.swing.MigLayout;

import com.documentum.fc.client.DfQuery;
import com.documentum.fc.client.IDfCollection;
import com.documentum.fc.client.IDfQuery;
import com.documentum.fc.client.IDfSession;
import com.documentum.fc.common.DfException;
import com.documentum.fc.common.DfLogger;


/**
 *
 * @author  Administrator
 */
public class AttributeSelectorFrameCOPY extends javax.swing.JFrame {

    private DefaultListModel selectedModel;
    private DefaultListModel allModel;
    private Vector listattributes;
    private ActionListener actionlistener;
    private VisibleAttributeData data;
    DocuSessionManager smanager;
    /** Creates new form AttributeSelectorFrame */
    public AttributeSelectorFrameCOPY() {
    	setPreferredSize(new Dimension(234, 234));
    	setMinimumSize(new Dimension(601, 500));
    	setResizable(false);
        initComponents();
    }

    public AttributeSelectorFrameCOPY(Vector _listattributes, ActionListener al,VisibleAttributeData _data) {
        initComponents();
        smanager = DocuSessionManager.getInstance();
        listattributes = _listattributes;
        selectedModel = new DefaultListModel();
        allModel = new DefaultListModel();
        actionlistener = al;
        data=_data;
        initVisibleAttributes();
        initAllAttributes();

    }

    public void initVisibleAttributes() {
        for (int i = 0; i < listattributes.size(); i++) {
            selectedModel.addElement(listattributes.get(i));
        }
        lstVisible.setModel(selectedModel);
    }

    public void initAllAttributes() {
        IDfCollection col = null;
        IDfSession session = null;
        try {
            session = smanager.getSession();
            IDfQuery query = new DfQuery();
            query.setDQL("select attr_name from dm_type where name = 'dm_sysobject' order by attr_name");
            col = query.execute(session, DfQuery.DF_CACHE_QUERY);
            while (col.next()) {
                allModel.addElement(col.getString("attr_name"));
            }
            lstAll.setModel(allModel);
        } catch (DfException ex) {
            DfLogger.error(this,  null, null, ex);
        } finally {
            if (col != null) {
                try {
                    col.close();
                } catch (DfException e) {
                	DfLogger.error(this,  null, null, e);
                }
            }
            if (session!=null)
                smanager.releaseSession(session);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBounds(10, 11, 575, 326);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Attribute Selector");
        getContentPane().setLayout(null);
        getContentPane().add(jPanel1);
        GridBagLayout gbl_jPanel1 = new GridBagLayout();
        gbl_jPanel1.columnWidths = new int[]{221, 73, 134, 123, 0};
        gbl_jPanel1.rowHeights = new int[]{47, 82, 57, 97, 23, 0};
        gbl_jPanel1.columnWeights = new double[]{0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
        gbl_jPanel1.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
        jPanel1.setLayout(gbl_jPanel1);
        cmdAddOrderBy = new javax.swing.JButton();
        
                cmdAddOrderBy.setText("Add");
                cmdAddOrderBy.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton5ActionPerformed(evt);
                    }
                });
                cmdAddVisible = new javax.swing.JButton();
                
                        cmdAddVisible.setText("Add");
                        cmdAddVisible.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cmdAddVisibleActionPerformed(evt);
                            }
                        });
                        jPanel4 = new javax.swing.JPanel();
                        jScrollPane1 = new javax.swing.JScrollPane();
                        lstAll = new javax.swing.JList();
                        
                                jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Attributes"));
                                
                                        lstAll.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                                        jScrollPane1.setViewportView(lstAll);
                                        
                                                org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
                                                jPanel4.setLayout(jPanel4Layout);
                                                jPanel4Layout.setHorizontalGroup(
                                                    jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                                );
                                                jPanel4Layout.setVerticalGroup(
                                                    jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                                                );
                                                GridBagConstraints gbc_jPanel4 = new GridBagConstraints();
                                                gbc_jPanel4.fill = GridBagConstraints.BOTH;
                                                gbc_jPanel4.insets = new Insets(0, 0, 5, 5);
                                                gbc_jPanel4.gridheight = 4;
                                                gbc_jPanel4.gridx = 0;
                                                gbc_jPanel4.gridy = 0;
                                                jPanel1.add(jPanel4, gbc_jPanel4);
                        GridBagConstraints gbc_cmdAddVisible = new GridBagConstraints();
                        gbc_cmdAddVisible.anchor = GridBagConstraints.SOUTH;
                        gbc_cmdAddVisible.fill = GridBagConstraints.HORIZONTAL;
                        gbc_cmdAddVisible.insets = new Insets(0, 0, 5, 5);
                        gbc_cmdAddVisible.gridx = 1;
                        gbc_cmdAddVisible.gridy = 0;
                        jPanel1.add(cmdAddVisible, gbc_cmdAddVisible);
                jPanel5 = new javax.swing.JPanel();
                
                        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Visible Attributes"));
                                        GridBagConstraints gbc_jPanel5 = new GridBagConstraints();
                                        gbc_jPanel5.fill = GridBagConstraints.BOTH;
                                        gbc_jPanel5.insets = new Insets(0, 0, 5, 0);
                                        gbc_jPanel5.gridheight = 2;
                                        gbc_jPanel5.gridwidth = 2;
                                        gbc_jPanel5.gridx = 2;
                                        gbc_jPanel5.gridy = 0;
                                        jPanel1.add(jPanel5, gbc_jPanel5);
                                        GridBagLayout gbl_jPanel5 = new GridBagLayout();
                                        gbl_jPanel5.columnWidths = new int[]{251, 0};
                                        gbl_jPanel5.rowHeights = new int[]{105, 0};
                                        gbl_jPanel5.columnWeights = new double[]{0.0, Double.MIN_VALUE};
                                        gbl_jPanel5.rowWeights = new double[]{0.0, Double.MIN_VALUE};
                                        jPanel5.setLayout(gbl_jPanel5);
                                        jScrollPane2 = new javax.swing.JScrollPane();
                                        lstVisible = new javax.swing.JList();
                                        
                                                lstVisible.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                                                jScrollPane2.setViewportView(lstVisible);
                                                GridBagConstraints gbc_jScrollPane2 = new GridBagConstraints();
                                                gbc_jScrollPane2.fill = GridBagConstraints.BOTH;
                                                gbc_jScrollPane2.gridx = 0;
                                                gbc_jScrollPane2.gridy = 0;
                                                jPanel5.add(jScrollPane2, gbc_jScrollPane2);
                cmdRemoveVisible = new javax.swing.JButton();
                
                        cmdRemoveVisible.setText("Remove");
                        cmdRemoveVisible.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cmdRemoveVisibleActionPerformed(evt);
                            }
                        });
                        GridBagConstraints gbc_cmdRemoveVisible = new GridBagConstraints();
                        gbc_cmdRemoveVisible.fill = GridBagConstraints.HORIZONTAL;
                        gbc_cmdRemoveVisible.anchor = GridBagConstraints.NORTH;
                        gbc_cmdRemoveVisible.insets = new Insets(0, 0, 5, 5);
                        gbc_cmdRemoveVisible.gridx = 1;
                        gbc_cmdRemoveVisible.gridy = 1;
                        jPanel1.add(cmdRemoveVisible, gbc_cmdRemoveVisible);
                GridBagConstraints gbc_cmdAddOrderBy = new GridBagConstraints();
                gbc_cmdAddOrderBy.anchor = GridBagConstraints.SOUTH;
                gbc_cmdAddOrderBy.fill = GridBagConstraints.HORIZONTAL;
                gbc_cmdAddOrderBy.insets = new Insets(0, 0, 5, 5);
                gbc_cmdAddOrderBy.gridx = 1;
                gbc_cmdAddOrderBy.gridy = 2;
                jPanel1.add(cmdAddOrderBy, gbc_cmdAddOrderBy);
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstOrderBy = new javax.swing.JList();
        chkDescending = new javax.swing.JCheckBox();
        
                jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Order by"));
                
                        lstOrderBy.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                        jScrollPane3.setViewportView(lstOrderBy);
                        
                                chkDescending.setText("Descending order");
                                        GridBagConstraints gbc_jPanel6 = new GridBagConstraints();
                                        gbc_jPanel6.fill = GridBagConstraints.BOTH;
                                        gbc_jPanel6.insets = new Insets(0, 0, 5, 0);
                                        gbc_jPanel6.gridheight = 2;
                                        gbc_jPanel6.gridwidth = 2;
                                        gbc_jPanel6.gridx = 2;
                                        gbc_jPanel6.gridy = 2;
                                        jPanel1.add(jPanel6, gbc_jPanel6);
                                        jPanel6.setLayout(new MigLayout("", "[251px]", "[109.00px][61px]"));
                                        jPanel6.add(jScrollPane3, "cell 0 0,grow");
                                        jPanel6.add(chkDescending, "cell 0 1,growx,aligny bottom");
        jButton6 = new javax.swing.JButton();
        
                jButton6.setText("Remove");
                GridBagConstraints gbc_jButton6 = new GridBagConstraints();
                gbc_jButton6.fill = GridBagConstraints.HORIZONTAL;
                gbc_jButton6.anchor = GridBagConstraints.NORTH;
                gbc_jButton6.insets = new Insets(0, 0, 5, 5);
                gbc_jButton6.gridx = 1;
                gbc_jButton6.gridy = 3;
                jPanel1.add(jButton6, gbc_jButton6);
        
        button = new JButton();
        button.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        	}
        });
        button.setText("Save");
        GridBagConstraints gbc_button = new GridBagConstraints();
        gbc_button.anchor = GridBagConstraints.NORTHEAST;
        gbc_button.insets = new Insets(0, 0, 0, 5);
        gbc_button.gridx = 2;
        gbc_button.gridy = 4;
        jPanel1.add(button, gbc_button);
        
        button_1 = new JButton();
        button_1.setText("Cancel");
        GridBagConstraints gbc_button_1 = new GridBagConstraints();
        gbc_button_1.anchor = GridBagConstraints.NORTHWEST;
        gbc_button_1.gridx = 3;
        gbc_button_1.gridy = 4;
        jPanel1.add(button_1, gbc_button_1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cmdAddVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddVisibleActionPerformed

        String selected = (String) lstAll.getSelectedValue();

        if (!selectedModel.contains(selected)) {
            selectedModel.addElement(selected);
            lstVisible.validate();
        }
    }//GEN-LAST:event_cmdAddVisibleActionPerformed

    private void cmdRemoveVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRemoveVisibleActionPerformed

        String selected = (String) lstVisible.getSelectedValue();

        if (selectedModel.contains(selected)) {
            selectedModel.removeElement(selected);
            lstVisible.validate();
        }
        
    }//GEN-LAST:event_cmdRemoveVisibleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkDescending;
    private javax.swing.JButton cmdAddVisible;
    private javax.swing.JButton cmdRemoveVisible;
    private javax.swing.JButton cmdAddOrderBy;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList lstAll;
    private javax.swing.JList lstOrderBy;
    private javax.swing.JList lstVisible;
    private JButton button;
    private JButton button_1;
    // End of variables declaration//GEN-END:variables

    public VisibleAttributeData getData() {
        return data;
    }
}
