/*
 * DumpFrame.java
 *
 * Created on 27. lokakuuta 2006, 21:36
 */
package org.quickclient.gui;

import java.awt.Font;

import org.quickclient.classes.DocuSessionManager;
import org.quickclient.classes.SwingHelper;

import com.documentum.fc.client.IDfPersistentObject;
import com.documentum.fc.client.IDfSession;
import com.documentum.fc.common.DfException;
import com.documentum.fc.common.DfLogger;
import com.documentum.fc.common.IDfId;


/**
 * 
 * @author Administrator
 */
public class DumpFrame extends javax.swing.JFrame {

	DocuSessionManager smanager;

	/**
	 * Creates new form DumpFrame
	 */
	public DumpFrame() {
		initComponents();
		smanager = DocuSessionManager.getInstance();
		Font font = new Font("Courier", Font.PLAIN, 12);
		textArea1.setFont(font);
	}

	public void initData() {

		IDfSession session = null;
		try {
			session = smanager.getSession();
			if (id != null) {
				IDfPersistentObject obj = (IDfPersistentObject) session.getObject(id);
				if (obj != null) {
					textArea1.setText(obj.dump());
					textArea1.validate();
					this.setTitle("Dump of: " + id.getId());
				} else {
					DfLogger.error(this, "null obj", null, null);
					SwingHelper.showErrorMessage("null object", "Failed to fetch object.");
				}
			} else {
				SwingHelper.showErrorMessage("null id", "Failed to fetch object.");				
			}
		} catch (DfException e) {
			DfLogger.error(this, e.getMessage(), null, e);
			SwingHelper.showErrorMessage("Error", e.getMessage());
		} finally {
			if (session != null) {
				smanager.releaseSession(session);
			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		textArea1 = new java.awt.TextArea();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setLocationByPlatform(true);

		jButton1.setMnemonic('C');
		jButton1.setText("Close");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton1MouseClicked(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup()
						.add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(layout.createSequentialGroup().addContainerGap().add(textArea1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
								.add(layout.createSequentialGroup().add(204, 204, 204).add(jButton1))).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(org.jdesktop.layout.GroupLayout.TRAILING,
				layout.createSequentialGroup().addContainerGap().add(textArea1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jButton1).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		this.setVisible(false);
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton1MouseClicked
		// TODO add your handling code here:

	}// GEN-LAST:event_jButton1MouseClicked

	/**
	 * @param args
	 *            the command line arguments
	 */
	private IDfId id;
	private String strID;

	public void setstrID(String strid) {
		this.strID = strid;
	}

	public void setId(IDfId id) {
		this.id = id;
	}

	public void setTextArea1(java.awt.TextArea textArea1) {
		this.textArea1 = textArea1;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private java.awt.TextArea textArea1;
	// End of variables declaration//GEN-END:variables
}
