/*
 * JobListFrame.java
 *
 * Created on 12. marraskuuta 2006, 16:58
 */
package org.quickclient.gui;

import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.util.Vector;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

import org.apache.log4j.Logger;
import org.quickclient.classes.DocuSessionManager;
import org.quickclient.classes.DokuData;
import org.quickclient.classes.ExJTextArea;
import org.quickclient.classes.SwingHelper;

import com.documentum.fc.client.DfQuery;
import com.documentum.fc.client.IDfCollection;
import com.documentum.fc.client.IDfPersistentObject;
import com.documentum.fc.client.IDfQuery;
import com.documentum.fc.client.IDfSession;
import com.documentum.fc.client.IDfSysObject;
import com.documentum.fc.common.DfException;
import com.documentum.fc.common.DfId;
import com.documentum.fc.common.IDfId;


class CustomTableCellRenderer extends DefaultTableCellRenderer {

	@Override
	public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
		Component cell = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
		if (column == 0) {
			TableModel model = table.getModel();
			Integer activity = (Integer) model.getValueAt(row, 3);
			// //System.out.println(activity);
			Font font = cell.getFont();
			if (activity.intValue() == 0) {
				cell.setForeground(Color.BLUE);
				Font font2 = font.deriveFont(Font.BOLD);
				cell.setFont(font2);
			} else if (activity.intValue() == 2) {
				cell.setForeground(Color.MAGENTA);
				Font font2 = font.deriveFont(Font.BOLD);
				cell.setFont(font2);
			} else {
				cell.setForeground(Color.BLACK);
			}
		}
		return cell;
	}
}

/**
 * 
 * @author Administrator
 */
public class JobListFrame extends javax.swing.JFrame {

	DocuSessionManager smanager;
	Logger log = Logger.getLogger(JobListFrame.class);

	/** Creates new form JobListFrame */
	public JobListFrame() {
		initComponents();
		this.jScrollPane1.getViewport().setBackground(Color.WHITE);
		smanager = DocuSessionManager.getInstance();
		initCombo();
		DefaultTableModel xx = new DefaultTableModel() {

			@Override
			public boolean isCellEditable(int row, int column) {
				return false;
			}
		};
		setJobModel(xx);
		getJobModel().addColumn("Job Name");
		getJobModel().addColumn("Description");
		getJobModel().addColumn("Status");
		getJobModel().addColumn("data");
		getJobModel().addColumn("activity");
		tblJobTable.setAutoCreateColumnsFromModel(false);
		tblJobTable.setModel(getJobModel());
		TableCellRenderer renderer = new CustomTableCellRenderer();
		try {
			tblJobTable.setDefaultRenderer(Class.forName("java.lang.Object"), renderer);
		} catch (ClassNotFoundException ex) {
			log.error(ex);
		}
		TableColumn col1 = tblJobTable.getColumnModel().getColumn(0);
		col1.setPreferredWidth(250);
		col1.setMaxWidth(250);
		int delay = 5000; // milliseconds
		ActionListener taskPerformer = new ActionListener() {

			public void actionPerformed(ActionEvent evt) {
				if (chkAutoRefresh.isSelected()) {
					updateDisplay(cmbJobCombo.getSelectedItem().toString());
				}
			}
		};
		new Timer(delay, taskPerformer).start();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		popUpJOB = new javax.swing.JPopupMenu();
		mnuActivate = new javax.swing.JMenuItem();
		mnuInActivate = new javax.swing.JMenuItem();
		mnuRunNow = new javax.swing.JMenuItem();
		mnuEditJob = new javax.swing.JMenuItem();
		mnuViewLog = new javax.swing.JMenuItem();
		jSeparator1 = new javax.swing.JSeparator();
		mnuDelete = new javax.swing.JMenuItem();
		jPanel4 = new javax.swing.JPanel();
		jPanel4.setBounds(10, 10, 430, 330);
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtJobbName = new javax.swing.JTextField();
		txtJobCategory = new javax.swing.JTextField();
		chkActive = new javax.swing.JCheckBox();
		chkInactivate = new javax.swing.JCheckBox();
		txtMaxIter = new javax.swing.JTextField();
		txtMethod = new javax.swing.JTextField();
		cmdSelectMethod = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();

		jLabel3 = new javax.swing.JLabel();
		txtTraceLevel = new javax.swing.JTextField();
		chkPassStandard = new javax.swing.JCheckBox();
		jLabel4 = new javax.swing.JLabel();
		txtDesignatedServer = new javax.swing.JTextField();

		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jDateChooserExpirantionDate = new com.toedter.calendar.JDateChooser();
		jDateChooserActivationDate = new com.toedter.calendar.JDateChooser();
		jCheckBox4 = new javax.swing.JCheckBox();
		jLabel11 = new javax.swing.JLabel();
		jTextField7 = new javax.swing.JTextField();
		cmbTiming = new javax.swing.JComboBox();
		txtRunInterval = new javax.swing.JTextField();
		jLabel12 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jPanel1.setBounds(30, 527, 410, 40);
		cmdSave = new javax.swing.JButton();
		cmdClose = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblJobTable = new javax.swing.JTable();
		cmbJobCombo = new javax.swing.JComboBox();
		jButton7 = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		chkAutoRefresh = new javax.swing.JCheckBox();
		jButton8 = new javax.swing.JButton();

		mnuActivate.setText("Activate");
		mnuActivate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuActivateActionPerformed(evt);
			}
		});
		popUpJOB.add(mnuActivate);

		mnuInActivate.setText("InActivate");
		mnuInActivate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuInActivateActionPerformed(evt);
			}
		});
		popUpJOB.add(mnuInActivate);

		mnuRunNow.setText("Run Now!");
		mnuRunNow.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuRunNowActionPerformed(evt);
			}
		});
		popUpJOB.add(mnuRunNow);

		mnuEditJob.setText("Edit this Job");
		mnuEditJob.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuEditJobActionPerformed(evt);
			}
		});
		popUpJOB.add(mnuEditJob);

		mnuViewLog.setText("View Log");
		mnuViewLog.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuViewLogActionPerformed(evt);
			}
		});
		popUpJOB.add(mnuViewLog);
		popUpJOB.add(jSeparator1);

		mnuDelete.setText("Delete");
		mnuDelete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuDeleteActionPerformed(evt);
			}
		});
		popUpJOB.add(mnuDelete);


		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Job Manager");
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setLocationByPlatform(true);
		setResizable(false);

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Job List"));

		tblJobTable.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Name", "Status" }) {
			boolean[] canEdit = new boolean[] { false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		tblJobTable.setSelectionBackground(new java.awt.Color(115, 115, 255));
		tblJobTable.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				tblJobTableMouseReleased(evt);
			}
		});
		jScrollPane1.setViewportView(tblJobTable);

		cmbJobCombo.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
			public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
				cmbJobComboMouseWheelMoved(evt);
			}
		});

		jButton7.setText("New Job");
		jButton7.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		jButton1.setMnemonic('e');
		jButton1.setText("Edit");
		jButton1.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton3.setMnemonic('r');
		jButton3.setText("Run now");
		jButton3.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setMnemonic('a');
		jButton4.setText("Activate");
		jButton4.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton5.setMnemonic('i');
		jButton5.setText("Inactivate");
		jButton5.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton6.setMnemonic('d');
		jButton6.setText("Delete");
		jButton6.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		chkAutoRefresh.setText("Refresh automatically");
		chkAutoRefresh.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		chkAutoRefresh.setMargin(new java.awt.Insets(0, 0, 0, 0));
		chkAutoRefresh.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				chkAutoRefreshActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout gl_jPanel2 = new org.jdesktop.layout.GroupLayout(jPanel2);
		jPanel2.setLayout(gl_jPanel2);
		gl_jPanel2.setHorizontalGroup(gl_jPanel2.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				gl_jPanel2
						.createSequentialGroup()
						.addContainerGap()
						.add(gl_jPanel2
								.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
								.add(gl_jPanel2.createSequentialGroup().add(cmbJobCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jButton7)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jButton1).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jButton3).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jButton4)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jButton5).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jButton6).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(chkAutoRefresh))).addContainerGap()));

		gl_jPanel2.linkSize(new java.awt.Component[] { jButton1, jButton3, jButton4, jButton5, jButton6, jButton7 }, org.jdesktop.layout.GroupLayout.HORIZONTAL);

		gl_jPanel2.setVerticalGroup(gl_jPanel2.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				gl_jPanel2
						.createSequentialGroup()
						.add(gl_jPanel2.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(cmbJobCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(jButton7).add(jButton1)
								.add(jButton3).add(jButton4).add(jButton5).add(jButton6).add(chkAutoRefresh)).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE).addContainerGap()));

		jButton8.setText("Close");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(layout.createSequentialGroup().addContainerGap(748, Short.MAX_VALUE).add(jButton8).addContainerGap())
				.add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(org.jdesktop.layout.GroupLayout.TRAILING,
				layout.createSequentialGroup().add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jButton8).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void cmbJobComboMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {// GEN-FIRST:event_cmbJobComboMouseWheelMoved

		int maxindex = cmbJobCombo.getItemCount();
		if (evt.getWheelRotation() > 0) {
			int index = cmbJobCombo.getSelectedIndex();
			if (index < maxindex - 1) {
				cmbJobCombo.setSelectedIndex(index + 1);
			}
		} else {
			int index = cmbJobCombo.getSelectedIndex();
			if (index > 0) {
				cmbJobCombo.setSelectedIndex(index - 1);
			}
		}
	}// GEN-LAST:event_cmbJobComboMouseWheelMoved


	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton7ActionPerformed
		IDfSession session = null;
		String newid = "";
		try {
			session = smanager.getSession();
			IDfPersistentObject job = session.newObject("dm_job");
			job.setString("object_name", "new job");
			job.save();
			newid = job.getObjectId().toString();
		} catch (DfException ex) {
			log.error(ex);
		} finally {
			if (session != null) {
				smanager.releaseSession(session);
			}
		}
		editJob(newid);

	}// GEN-LAST:event_jButton7ActionPerformed

	private void mnuDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuDeleteActionPerformed

		// TODO tämä koodi on duplikaattina kahdessa paikkaa
		int rowid = tblJobTable.getSelectedRow();
		if (rowid == -1)
			return;
		Vector v = (Vector) getJobModel().getDataVector().elementAt(rowid);
		DokuData data = (DokuData) v.elementAt(2);
		String id = data.getObjID();
		IDfId iidee = new DfId(id);
		IDfSession session = null;
		Cursor cur = new Cursor(Cursor.WAIT_CURSOR);

		setCursor(cur);
		try {
			session = smanager.getSession();
			IDfPersistentObject obj = session.getObject(iidee);
			int answer = JOptionPane.showConfirmDialog(this, "Destroy Job: " + obj.getString("object_name") + ". Are you sure??", "Confirm", JOptionPane.YES_NO_OPTION);
			if (answer == JOptionPane.YES_OPTION) {
				obj.destroy();
			}
		} catch (DfException ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage(), "Error occured!", JOptionPane.ERROR_MESSAGE);
			log.error(ex);
		} finally {
			if (session != null) {
				smanager.releaseSession(session);
			}
			Cursor cur2 = new Cursor(Cursor.DEFAULT_CURSOR);
			setCursor(cur2);
		}
	}// GEN-LAST:event_mnuDeleteActionPerformed

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
		this.inactivateJob();
	}// GEN-LAST:event_jButton5ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
		this.activateJob();
	}// GEN-LAST:event_jButton4ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		this.runNowJob();
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		this.editJob("");
	}// GEN-LAST:event_jButton1ActionPerformed


	private void editJob(String newid) {
		IDfId iidee = null;
		if (newid.length() < 1) {
			int rowid = tblJobTable.getSelectedRow();
			if (rowid == -1)
				return;
			Vector v = (Vector) getJobModel().getDataVector().elementAt(rowid);
			DokuData data = (DokuData) v.elementAt(2);
			String id = data.getObjID();
			
			iidee = new DfId(id);
		} else {
			
			iidee = new DfId(newid);
		}
		JobEditor editor = new JobEditor(iidee);
		editor.setVisible(true);
	}

	private void mnuEditJobActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuEditJobActionPerformed
		editJob("");
	}// GEN-LAST:event_mnuEditJobActionPerformed

	private void tblJobTableMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tblJobTableMouseReleased
		int butt = evt.getButton();
		if (butt == MouseEvent.BUTTON3) {
			popUpJOB.show(evt.getComponent(), evt.getX(), evt.getY());
		}
	}// GEN-LAST:event_tblJobTableMouseReleased

	private void runNowJob() {
		int rowid = tblJobTable.getSelectedRow();
		if (rowid==-1)
			return;
		Vector v = (Vector) getJobModel().getDataVector().elementAt(rowid);
		DokuData data = (DokuData) v.elementAt(2);
		String id = data.getObjID();
		IDfId iidee = new DfId(id);
		IDfSession session = null;
		IDfCollection col = null;
		try {
			session = smanager.getSession();
			IDfQuery query = new DfQuery();
			query.setDQL("update dm_job object set run_now = 1 where r_object_id = '" + id + "'");
			col = query.execute(session, DfQuery.DF_QUERY);
			SwingHelper.showMessage("run_now attribute set to true.");

		} catch (DfException ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage(), "Error occured!", JOptionPane.ERROR_MESSAGE);

			log.error(ex);
		} finally {
			if (session != null) {
				smanager.releaseSession(session);
			}
			if (col != null) {
				try {
					col.close();
				} catch (DfException ex) {
					log.error(ex);
				}
			}
		}
	}

	private void mnuRunNowActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuRunNowActionPerformed

		this.runNowJob();
	}// GEN-LAST:event_mnuRunNowActionPerformed

	private void inactivateJob() {
		Cursor cur = new Cursor(Cursor.WAIT_CURSOR);

		setCursor(cur);
		int rowid = tblJobTable.getSelectedRow();
		if (rowid == -1)
			return;
		Vector v = (Vector) getJobModel().getDataVector().elementAt(rowid);
		DokuData data = (DokuData) v.elementAt(2);
		String id = data.getObjID();
		IDfId iidee = new DfId(id);
		IDfSession session = null;
		try {
			session = smanager.getSession();
			IDfPersistentObject obj = session.getObject(iidee);
			obj.setBoolean("is_inactive", true);
			obj.save();
		} catch (DfException ex) {
			log.error(ex);
			JOptionPane.showMessageDialog(null, ex.getMessage(), "Error occured!", JOptionPane.ERROR_MESSAGE);

		} finally {
			smanager.releaseSession(session);
		}
		Cursor cur2 = new Cursor(Cursor.DEFAULT_CURSOR);

		setCursor(cur2);
		updateDisplay(cmbJobCombo.getSelectedItem().toString());
	}

	private void mnuInActivateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuInActivateActionPerformed

		this.inactivateJob();
	}// GEN-LAST:event_mnuInActivateActionPerformed

	private void activateJob() {
		int rowid = tblJobTable.getSelectedRow();
		if (rowid == -1)
			return;
		Cursor cur = new Cursor(Cursor.WAIT_CURSOR);
		setCursor(cur);
		Vector v = (Vector) getJobModel().getDataVector().elementAt(rowid);
		DokuData data = (DokuData) v.elementAt(2);
		String id = data.getObjID();
		IDfId iidee = new DfId(id);
		IDfSession session = null;

		try {
			session = smanager.getSession();
			IDfPersistentObject obj = session.getObject(iidee);
			obj.setInt("is_inactive", 0);
			obj.save();
		} catch (DfException ex) {
			log.error(ex);
			JOptionPane.showMessageDialog(null, ex.getMessage(), "Error occured!", JOptionPane.ERROR_MESSAGE);

		} finally {
			if (session != null) {
				smanager.releaseSession(session);
			}
		}
		Cursor cur2 = new Cursor(Cursor.DEFAULT_CURSOR);

		setCursor(cur2);
		updateDisplay(cmbJobCombo.getSelectedItem().toString());
	}

	private void mnuActivateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuActivateActionPerformed
		this.activateJob();

	}// GEN-LAST:event_mnuActivateActionPerformed

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton8ActionPerformed
		this.dispose();
	}// GEN-LAST:event_jButton8ActionPerformed

	private void mnuViewLogActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuViewLogActionPerformed
		int rowid = tblJobTable.getSelectedRow();
		if (rowid == -1)
			return;
		Vector v = (Vector) getJobModel().getDataVector().elementAt(rowid);
		DokuData data = (DokuData) v.elementAt(2);
		String id = data.getObjID();
		IDfId iidee = new DfId(id);
		IDfSession session = null;
		Cursor cur = new Cursor(Cursor.WAIT_CURSOR);

		setCursor(cur);
		try {
			session = smanager.getSession();
			IDfPersistentObject obj = session.getObject(iidee);
			String logid = obj.getString("a_last_document_id");
			if (logid.equals("0000000000000000")) {
			} else {
				IDfSysObject sobj = (IDfSysObject) session.getObject(new DfId(logid));
				String filePath = sobj.getFile(null);
				File fileToOpen = new File(filePath);

				Desktop.getDesktop().open(fileToOpen);

			}
		} catch (IOException ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage(), "Error occured!", JOptionPane.ERROR_MESSAGE);

			log.error(ex);
		} catch (DfException ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage(), "Error occured!", JOptionPane.ERROR_MESSAGE);

			log.error(ex);
		} finally {
			if (session != null) {
				smanager.releaseSession(session);
			}
			Cursor cur2 = new Cursor(Cursor.DEFAULT_CURSOR);

			setCursor(cur2);
		}
		updateDisplay(cmbJobCombo.getSelectedItem().toString());
	}// GEN-LAST:event_mnuViewLogActionPerformed

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton6ActionPerformed
		int rowid = tblJobTable.getSelectedRow();
		if (rowid==-1)
			return;
		Vector v = (Vector) getJobModel().getDataVector().elementAt(rowid);
		
		DokuData data = (DokuData) v.elementAt(2);
		String id = data.getObjID();
		IDfId iidee = new DfId(id);
		IDfSession session = null;
		Cursor cur = new Cursor(Cursor.WAIT_CURSOR);

		setCursor(cur);
		try {
			session = smanager.getSession();
			IDfPersistentObject obj = session.getObject(iidee);
			int answer = JOptionPane.showConfirmDialog(this, "Destroy Job: " + obj.getString("object_name") + ". Are you sure??", "Confirm", JOptionPane.YES_NO_OPTION);
			if (answer == JOptionPane.YES_OPTION) {
				obj.destroy();
			}
		} catch (DfException ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage(), "Error occured!", JOptionPane.ERROR_MESSAGE);

			log.error(ex);
		} finally {
			if (session != null) {
				smanager.releaseSession(session);
			}
			Cursor cur2 = new Cursor(Cursor.DEFAULT_CURSOR);

			setCursor(cur2);
		}
	}// GEN-LAST:event_jButton6ActionPerformed

	private void chkAutoRefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chkAutoRefreshActionPerformed
	// TODO add your handling code here:
	}// GEN-LAST:event_chkAutoRefreshActionPerformed

	public void initCombo() {
		Cursor cur = new Cursor(Cursor.WAIT_CURSOR);

		setCursor(cur);
		String strqry = "select distinct title from dm_job order by 1";
		IDfCollection col = null;
		IDfQuery qry = new DfQuery();
		qry.setDQL(strqry);
		IDfSession session = null;
		try {
			session = smanager.getSession();
			col = qry.execute(session, IDfQuery.DF_READ_QUERY);
			while (col.next()) {
				cmbJobCombo.addItem(col.getString("title"));
			}
			col.close();
		} catch (DfException ex) {
			log.error(ex);
		} finally {
			if (session != null) {
				smanager.releaseSession(session);
			}
			Cursor cur2 = new Cursor(Cursor.DEFAULT_CURSOR);

			setCursor(cur2);
		}
		cmbJobCombo.addItem("All Jobs");
		cmbJobCombo.addItem("Active Jobs");
		cmbJobCombo.addItem("Inactive Jobs");
		cmbJobCombo.addItem("Running Jobs");
		cmbJobCombo.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				JComboBox jc = (JComboBox) e.getSource();
				updateDisplay(jc.getSelectedItem().toString());
			}
		});
	}

	public void updateDisplay(String category) {
		Cursor cur = new Cursor(Cursor.WAIT_CURSOR);

		setCursor(cur);
		String strqry = "";
		if (category.equalsIgnoreCase("all jobs")) {
			strqry = "select object_name, r_object_id, subject, is_inactive, a_current_status,a_special_app from dm_job order by 1";
		} else if (category.equalsIgnoreCase("active jobs")) {
			strqry = "select object_name, r_object_id, subject, is_inactive, a_current_status,a_special_app from dm_job where is_inactive = 0 order by 1";
		} else if (category.equalsIgnoreCase("inactive jobs")) {
			strqry = "select object_name, r_object_id, subject, is_inactive, a_current_status,a_special_app from dm_job where is_inactive = 1 order by 1";
		} else if (category.equalsIgnoreCase("running jobs")) {
			strqry = "select object_name, r_object_id, subject, is_inactive, a_current_status,a_special_app from dm_job where a_special_app = 'agentexec' order by 1";
		} else {
			strqry = "select object_name, r_object_id, subject, is_inactive, a_current_status,a_special_app from dm_job where title = '" + category + "'  order by 1";
		}
		IDfCollection col = null;
		IDfQuery qry = new DfQuery();
		qry.setDQL(strqry);
		IDfSession session = null;
		try {
			session = smanager.getSession();
			col = qry.execute(session, IDfQuery.DF_READ_QUERY);
			getJobModel().setRowCount(0);
			while (col.next()) {
				Vector<Object> a = new Vector<Object>();
				a.add(col.getString("object_name"));
				a.add(col.getString("a_current_status"));
				DokuData data = new DokuData(col.getString("r_object_id"));
				a.add(data);
				Integer i = col.getInt("is_inactive");
				String asa = col.getString("a_special_app");
				if (asa.equals("agentexec")) {
					a.add(new Integer(2));
				} else {
					a.add(i);
				}
				getJobModel().addRow(a);
			}
		} catch (DfException ex) {
			log.error(ex);
		} finally {
			if (session != null) {
				smanager.releaseSession(session);
			}
			if (col != null) {
				try {
					col.close();
				} catch (DfException es) {
				}
			}
		}
		Cursor cur2 = new Cursor(Cursor.DEFAULT_CURSOR);

		setCursor(cur2);
		tblJobTable.validate();
	}

	public void updateDisplay() {
		Cursor cur = new Cursor(Cursor.WAIT_CURSOR);

		setCursor(cur);
		String strqry = "select object_name, r_object_id, subject, is_inactive, a_current_status from dm_job order by 1";
		IDfCollection col = null;
		IDfQuery qry = new DfQuery();
		qry.setDQL(strqry);
		IDfSession session = null;
		try {
			session = smanager.getSession();
			col = qry.execute(session, IDfQuery.DF_READ_QUERY);
			getJobModel().setRowCount(0);
			while (col.next()) {
				Vector<Object> a = new Vector<Object>();
				a.add(col.getString("object_name"));
				a.add(col.getString("a_current_status"));
				DokuData data = new DokuData(col.getString("r_object_id"));
				a.add(data);
				a.add(col.getInt("is_inactive"));
				getJobModel().addRow(a);
			}

		} catch (DfException ex) {
			log.error(ex);
		} finally {
			if (session != null) {
				smanager.releaseSession(session);
			}
			if (col != null) {
				try {
					col.close();
				} catch (DfException es) {
				}
			}
		}
		Cursor cur2 = new Cursor(Cursor.DEFAULT_CURSOR);

		setCursor(cur2);
		tblJobTable.validate();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	private DefaultTableModel jobModel;
	private String currentID;

	public DefaultTableModel getJobModel() {
		return jobModel;
	}

	public void setJobModel(DefaultTableModel jobModel) {
		this.jobModel = jobModel;
	}





	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JCheckBox chkActive;
	private javax.swing.JCheckBox chkAutoRefresh;
	private javax.swing.JCheckBox chkInactivate;
	private javax.swing.JComboBox cmbJobCombo;
	private javax.swing.JComboBox cmbTiming;
	private javax.swing.JButton cmdChooseServer;
	private javax.swing.JButton cmdClose;
	private javax.swing.JButton cmdSave;
	private javax.swing.JButton cmdSelectMethod;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JCheckBox chkPassStandard;
	private javax.swing.JCheckBox jCheckBox4;
	private com.toedter.calendar.JDateChooser jDateChooserActivationDate;
	private com.toedter.calendar.JDateChooser jDateChooserExpirantionDate;
	private com.toedter.calendar.JDateChooser jDateChooserNextRunDate;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTextField jTextField7;

	private javax.swing.JMenuItem mnuActivate;
	private javax.swing.JMenuItem mnuDelete;
	private javax.swing.JMenuItem mnuEditJob;
	private javax.swing.JMenuItem mnuInActivate;
	private javax.swing.JMenuItem mnuRunNow;
	private javax.swing.JMenuItem mnuViewLog;
	private javax.swing.JPopupMenu popUpJOB;
	private javax.swing.JTable tblJobTable;
	private ExJTextArea txtArgiments = null;
	private javax.swing.JTextField txtDesignatedServer;
	private javax.swing.JTextField txtJobCategory;
	private javax.swing.JTextField txtJobbName;
	private javax.swing.JTextField txtMaxIter;
	private javax.swing.JTextField txtMethod;
	private javax.swing.JTextField txtRunInterval;
	private javax.swing.JTextField txtTraceLevel;
	// End of variables declaration//GEN-END:variables
}
