/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TextViewer.java
 *
 * Created on 31.10.2009, 22:20:11
 */
package org.quickclient.gui;

import com.documentum.fc.client.IDfSession;
import com.documentum.fc.client.IDfSysObject;
import com.documentum.fc.common.DfException;
import com.documentum.fc.common.DfId;
import com.documentum.fc.common.DfLogger;
import com.documentum.fc.common.IDfId;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.awt.TextArea;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;

import org.quickclient.classes.DocuSessionManager;

import java.awt.Font;

/**
 *
 * @author Mika
 */
public class TextViewer extends javax.swing.JFrame {

    private String objid;
    private String contentType;

    public TextViewer(boolean showbuttons, String title) {

        initComponents();
        if (!showbuttons) {
        cmdSavenew.setVisible(false);
        cmdSave.setVisible(false);
        }
        this.setText(title);
        this.setSize(800, 600);
    }

    
    /** Creates new form TextViewer 
     * @wbp.parser.constructor*/
    public TextViewer(boolean showbuttons) {

        initComponents();
        if (!showbuttons) {
        cmdSavenew.setVisible(false);
        cmdSave.setVisible(false);
        }
        this.setSize(800, 600);
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public void setObjid(Object objid) {
        this.objid = (String) objid;
    }

    public void setText(String joo) {
        this.textArea.setText(joo);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cmdClose = new javax.swing.JButton();
        cmdSavenew = new javax.swing.JButton();
        cmdSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout gl_jPanel1 = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(gl_jPanel1);
        gl_jPanel1.setHorizontalGroup(
            gl_jPanel1.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );
        gl_jPanel1.setVerticalGroup(
            gl_jPanel1.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );
        
        textArea = new TextArea();
        textArea.setFont(new java.awt.Font("Courier New", Font.PLAIN, 11));
       jScrollPane1.setViewportView(textArea);

        cmdClose.setMnemonic('C');
        cmdClose.setText("Close");
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });

        cmdSavenew.setText("Save Changes as New Version");
        cmdSavenew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSavenewActionPerformed(evt);
            }
        });

        cmdSave.setText("Save Changes");
        cmdSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addGap(30)
        			.addComponent(cmdSave)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(cmdSavenew)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(cmdClose)
        			.addContainerGap())
        		.addComponent(jPanel1, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(cmdClose)
        				.addComponent(cmdSavenew)
        				.addComponent(cmdSave))
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed

        this.dispose();
    }//GEN-LAST:event_cmdCloseActionPerformed

    private void cmdSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSaveActionPerformed
        IDfSession session = null;
        DocuSessionManager smanager = DocuSessionManager.getInstance();

        try {
            session = smanager.getSession();
            IDfId id = new DfId(objid);
            IDfSysObject obj = (IDfSysObject) session.getObject(id);
            String currentContent = textArea.getText();
 
            byte[] b = currentContent.getBytes();
            ByteArrayOutputStream baos = new ByteArrayOutputStream(b.length);
            baos.write(b);
            obj.setContent(baos);
            if (obj.isCheckedOut()) {
                obj.saveLock();
            } else {
                obj.save();
            }
            this.dispose();
        } catch (DfException ex) {
        	DfLogger.error(this, ex.getMessage(), null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error occured!", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
        	DfLogger.error(this, ex.getMessage(), null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error occured!", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_cmdSaveActionPerformed

    private void cmdSavenewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSavenewActionPerformed
        IDfSession session = null;
        DocuSessionManager smanager = DocuSessionManager.getInstance();

        try {
            session = smanager.getSession();
            IDfId id = new DfId(objid);
            IDfSysObject obj = (IDfSysObject) session.getObject(id);
            String currentContent = textArea.getText();
            obj.checkout();
            byte[] b = currentContent.getBytes();
            ByteArrayOutputStream baos = new ByteArrayOutputStream(b.length);
            baos.write(b);
            obj.setContent(baos);
            if (obj.isCheckedOut()) {
                obj.saveLock();
            } else {
                obj.save();
            }
            obj.checkin(false, null);
            this.dispose();
        } catch (DfException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error occured!", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error occured!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cmdSavenewActionPerformed

    private javax.swing.JButton cmdClose;
    private javax.swing.JButton cmdSave;
    private javax.swing.JButton cmdSavenew;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private TextArea textArea;
    // End of variables declaration//GEN-END:variables
}
